### ISSUE TITLE
Return value of Olssonm\SwedishEntity\Organization::parseType() must be of the type string, null returned

### ISSUE THREAD

**Issue by tomsommer** [olssonm/swedish-entity#10]
/src/Organization.php line 149

Olssonm\SwedishEntity\Organization->__construct('012779-0293')

**Comment by olssonm** [comment]
Good catch. Not too sure if a Swedish organization number can start with a "0", trying find data on this. As "012779-0293" technically is a correct number, but can't be matched to a type of company/organization.

Do you know where 012779-0293 comes from, it did you just happen to stumble across this?

**Comment by olssonm** [comment]
Gotcha – thanks for the heads up! Will look into it and publish an update.
