### ISSUE TITLE
Provide strict validation

### ISSUE THREAD

**Issue by tomsommer** [olssonm/swedish-entity#6]
Would be nice with a way to run this validation without using the `::clean()` function, as this modifies data.

**Comment by olssonm** [comment]
Might be possible; what's your use case? Is it for validating input-data or data thats already existing/stored in a database – and in what scenario is this causing you issues? Just curious =)

The clean-method seems to make little to zero impact on the actual validation results. Will investigate and see what the idea behind this was at the get-go.

**Comment by olssonm** [comment]
@tomsommer A new release is available (https://github.com/olssonm/swedish-entity/releases/tag/v1.2.0) where the Clean-method is no longer automatically applied. 

Thank you for your feedback.
