### ISSUE TITLE
Type error when validating null values

### ISSUE THREAD

**Issue by jandreasn** [olssonm/swedish-entity#8]
Error message:
```
Olssonm\SwedishEntity\Organization::__construct(): Argument #1 ($orgNo) must be of type string, null given, 
called in /vendor/olssonm/swedish-entity/src/SwedishEntityServiceProvider.php on line 32
```

Happens when trying to validate a null value with against this rule:
```
'organization_identity_number' => [
    'required_with:company_name',
    'entity:organization',
],  
```

**Comment by olssonm** [comment]
This happens when company_name is null I assume? Try:

```php
'organization_identity_number' => [
    'required_with:company_name',
    'nullable', // Field can be null, i.e. optional
    'entity:organization',
],  
```

Else the validator will try to validate even is there is no value to try the validation against.

**Comment by jandreasn** [comment]
That's correct, `company_name` did not exist when testing this so sure, adding nullable could be a solution.

But I still don't think the validator should throw an error/exception on null values. This did not happen when we were using olssonm/identity-number. I believe the difference might be that this return is missing in the new package: https://github.com/olssonm/identity-number/blob/master/src/Validator.php#L56

**Comment by olssonm** [comment]
Yes, there's quite a few differences from olssonm/identity-number. This package uses [personnummer/php](https://github.com/personnummer/php) as an underlying library, which in turn does also not allow null-values on new instances – and to be somewhat coherent it is enforced here too.

But I'll look into returning false on these errors when using the Laravel validator as I can understand that they can be bothersome – even though a null value should never reach the validator, there are other validation rules for that. Give me some time and I'll see what I can come up with =)

**Comment by jandreasn** [comment]
Great. Thanks!

**Comment by olssonm** [comment]
@jandreasn A new release (v1.3.0, [link](https://github.com/olssonm/swedish-entity/releases/tag/v1.3.0)) is now available which allows empty values for the Laravel-validator. 

Please try it out and see if it works in your case as expected.
